[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["echo 'Backend only - no frontend build needed'"]

[start]
cmd = "cd server && npm start"
